# proto2

> Having completed "API Acquaintence" in proto1, aim is to

* [ ] understand data structure for entries
* [ ] understand data structure for tags
* [ ] _develop and test_ approaches to atomizing tags

In [1]:
import sys
import pinboard
from ruamel.yaml import YAML
from time import sleep
from random import sample, random
import pandas as pd

In [2]:
yaml=YAML(typ='safe')

In [3]:
with open("data/keys/pbkey.yaml") as kh:
    fin = kh.read()
    config = yaml.load(fin)

In [4]:
pb = pinboard.Pinboard(config.get('uname') + ":" + config.get("key"))
type(pb)

pinboard.pinboard.Pinboard

## figure out TAGS data structure

In [6]:
tags_pb = pb.tags.get()
print("type of tags_pb is", type(tags_pb))

type of tags_pb is <class 'list'>

In [7]:
print("type of an item of tags_pb is", type(tags_pb[0]))

type of an item of tags_pb is <class 'pinboard.pinboard.Tag'>

In [8]:
dir(tags_pb[0])

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'count',
 'name']

In [9]:
print("type of an item.count of tags_pb is", type(tags_pb[0].count))

type of an item.count of tags_pb is <class 'int'>

In [10]:
print("type of an item.name of tags_pb is", type(tags_pb[0].name))

type of an item.name of tags_pb is <class 'str'>

In [11]:
tags_df = pd.DataFrame([[_.name, _.count] for _ in tags_pb], columns=["tag_in", "count"])

In [12]:
tags_df

                      tag_in  count
0                 $chuckable     41
1           $chuckable(2016)      3
2                $read-often      4
3                        $rr     52
4            &amp;amp;advice      2
5           &amp;amp;article      5
6              &amp;amp;blog      2
7              &amp;amp;book      2
8       &amp;amp;book-review      1
9      &amp;amp;cheat-sheets      2
10            &amp;amp;class      3
11           &amp;amp;course      1
12    &amp;amp;documentation      2
13        &amp;amp;explainer      1
14            &amp;amp;guide      2
15           &amp;amp;how-to      3
16      &amp;amp;inspiration      1
17             &amp;amp;list      1
18     &amp;amp;long-article      2
19           &amp;amp;manual      3
20         &amp;amp;merchant      1
21          &amp;amp;op_inst      1
22            &amp;amp;paper      1
23              &amp;amp;pdf      1
24            &amp;amp;prank      1
25          &amp;amp;present      1
26     &amp;amp;presentation      2
27           &amp;amp;primer      4
28          &amp;amp;project      7
29        &amp;amp;r-package      5
...                      ...    ...
1956                    wise     60
1957               wish-list      1
1958                 wolfram      3
1959                    word      1
1960          word-embedding      3
1961                word2vec      4
1962               wordcloud      7
1963                   words      1
1964                    work      2
1965                workflow      2
1966               workflows      1
1967            working-copy      1
1968                 workout      1
1969    worth-of-information      1
1970                     wow      3
1971                 wrangle     11
1972                 writexl      1
1973                 writing      5
1974                    wwii      1
1975                   xcode      1
1976                 xlwings      1
1977                     xml      1
1978                     xts      2
1979         y-aware_scaling      2
1980                    yaml      6
1981               yeah-boii      1
1982                    yhat      8
1983                   youth      1
1984                     zen      1
1985                    zero      1

[1986 rows x 2 columns]

In [13]:
tags_df.to_excel("./data/tags.xlsx")

In [14]:
len([_ for _ in tags_df["tag_in"] if "." in _])

106

In [15]:
tags_df["dot_check"] = tags_df["tag_in"].str.contains("\.")

In [72]:
tags_df[tags_df["dot_check"]==True]

                                    tag_in  count dot_check
101                               .someday      1      True
217                           _app.firefox      1      True
218                  _app.pythonista.scene      1      True
219                             _app.spark      1      True
220                          _app.terminal      1      True
221                      _app.video-editor      1      True
224                              _coms.api      1      True
225                   _coms.best-practices      3      True
226                          _coms.cluster      1      True
227                    _coms.documentation      1      True
228                              _coms.hpc      1      True
229                        _coms.lang.bash      4      True
230                   _coms.lang.bash.tmux      1      True
231                  _coms.lang.javascript      7      True
232               _coms.lang.javascript.d3      1      True
233                       _coms.lang.julia      1      True
234                        _coms.lang.lisp      1      True
235                      _coms.lang.python      4      True
236     _coms.lang.python.ipython-notebook      1      True
237              _coms.lang.python.jupyter      2      True
238               _coms.lang.python.pandas      1      True
239   _coms.lang.python.pandas.categorical      1      True
240             _coms.lang.python.seaborne      1      True
241           _coms.lang.python.virtualenv      1      True
242                     _coms.lang.wolfram      1      True
243                           _coms.mashup      1      True
244                         _coms.parallel      3      True
245                    _coms.project.orery      1      True
246                    _coms.python.pytest      1      True
247                     _coms.python.scipy      1      True
...                                    ...    ...       ...
314                             _sci.astro      2      True
315                        _sci.astro.mars      1      True
316                       _sci.astro.orery      1      True
317                       _sci.astro.pluto      1      True
320                           _stat.causal      1      True
321                    _stat.control-chart      1      True
322                             _stat.corr      2      True
323                       _stat.covariance      1      True
324                          _stat.entropy      1      True
325                         _stat.forecast      1      True
326                              _stat.gam      1      True
327                              _stat.glm      2      True
328                    _stat.nonparametric      1      True
329                              _stat.pca      1      True
330                                _stat.r     15      True
331                          _stat.r.ggmap      1      True
332                            _stat.r.nlp      1      True
333                           _stat.r.plot      1      True
334                            _stat.r.roc      1      True
335                            _stat.r.sem      1      True
336                      _stat.r.smoothing      1      True
337                              _stat.sem      1      True
338                _stat.survival.analysis      1      True
339                 _stat.ts.kalman-filter      1      True
341                        _viz.dendrogram      1      True
342                    _viz.waterfall-plot      1      True
1169                               node.js      2      True
1270                         pivottable.js      1      True
1272                               pixi.js      1      True
1298                         povittable.js      1      True

[108 rows x 3 columns]

In [133]:
def dump_amps(strin):
    """remove all variations of &amp;"""
    evil = ["&amp;", "amp;"]
    for e in evil:
        strin = strin.replace(e, "")
    return strin
assert(dump_amps("&amp;")=="")
assert(dump_amps("&amp;amp;")=="")

In [134]:
def tag_check(strin):
    """split any tag containing a dot"""
    if strin[-3:] == ".js":
        candidates = strin
    else:
        candidates = [dump_amps(_) for _ in strin.split(".") if len(_) > 0]
    results = candidates
    return results

In [135]:
# tags_df["tag_splits"] = tags_df["tag_in"].str.split(".")
tags_df["tag_splits"] = tags_df["tag_in"].apply(tag_check)

In [136]:
tags_df[tags_df["dot_check"]==True]

,tag_in,count,dot_check,tag_splits
101,.someday,1,True,[someday]
217,_app.firefox,1,True,"[_app, firefox]"
218,_app.pythonista.scene,1,True,"[_app, pythonista, scene]"
219,_app.spark,1,True,"[_app, spark]"
220,_app.terminal,1,True,"[_app, terminal]"
221,_app.video-editor,1,True,"[_app, video-editor]"
224,_coms.api,1,True,"[_coms, api]"
225,_coms.best-practices,3,True,"[_coms, best-practices]"
226,_coms.cluster,1,True,"[_coms, cluster]"
227,_coms.documentation,1,True,"[_coms, documentation]"
228,_coms.hpc,1,True,"[_coms, hpc]"
229,_coms.lang.bash,4,True,"[_coms, lang, bash]"
230,_coms.lang.bash.tmux,1,True,"[_coms, lang, bash, tmux]"
231,_coms.lang.javascript,7,True,"[_coms, lang, javascript]"
232,_coms.lang.javascript.d3,1,True,"[_coms, lang, javascript, d3]"
233,_coms.lang.julia,1,True,"[_coms, lang, julia]"
234,_coms.lang.lisp,1,True,"[_coms, lang, lisp]"
235,_coms.lang.python,4,True,"[_coms, lang, python]"
236,_coms.lang.python.ipython-notebook,1,True,"[_coms, lang, python, ipython-notebook]"
237,_coms.lang.python.jupyter,2,True,"[_coms, lang, python, jupyter]"
238,_coms.lang.python.pandas,1,True,"[_coms, lang, python, pandas]"
239,_coms.lang.python.pandas.categorical,1,True,"[_coms, lang, python, pandas, categorical]"
240,_coms.lang.python.seaborne,1,True,"[_coms, lang, python, seaborne]"
241,_coms.lang.python.virtualenv,1,True,"[_coms, lang, python, virtualenv]"
242,_coms.lang.wolfram,1,True,"[_coms, lang, wolfram]"
243,_coms.mashup,1,True,"[_coms, mashup]"
244,_coms.parallel,3,True,"[_coms, parallel]"
245,_coms.project.orery,1,True,"[_coms, project, orery]"
246,_coms.python.pytest,1,True,"[_coms, python, pytest]"
247,_coms.python.scipy,1,True,"[_coms, python, scipy]"
...,...,...,...,...
314,_sci.astro,2,True,"[_sci, astro]"
315,_sci.astro.mars,1,True,"[_sci, astro, mars]"
316,_sci.astro.orery,1,True,"[_sci, astro, orery]"
317,_sci.astro.pluto,1,True,"[_sci, astro, pluto]"
320,_stat.causal,1,True,"[_stat, causal]"
321,_stat.control-chart,1,True,"[_stat, control-chart]"
322,_stat.corr,2,True,"[_stat, corr]"
323,_stat.covariance,1,True,"[_stat, covariance]"
324,_stat.entropy,1,True,"[_stat, entropy]"
325,_stat.forecast,1,True,"[_stat, forecast]"
326,_stat.gam,1,True,"[_stat, gam]"
327,_stat.glm,2,True,"[_stat, glm]"
328,_stat.nonparametric,1,True,"[_stat, nonparametric]"
329,_stat.pca,1,True,"[_stat, pca]"
330,_stat.r,15,True,"[_stat, r]"
331,_stat.r.ggmap,1,True,"[_stat, r, ggmap]"
332,_stat.r.nlp,1,True,"[_stat, r, nlp]"
333,_stat.r.plot,1,True,"[_stat, r, plot]"
334,_stat.r.roc,1,True,"[_stat, r, roc]"
335,_stat.r.sem,1,True,"[_stat, r, sem]"
336,_stat.r.smoothing,1,True,"[_stat, r, smoothing]"
337,_stat.sem,1,True,"[_stat, sem]"
338,_stat.survival.analysis,1,True,"[_stat, survival, analysis]"
339,_stat.ts.kalman-filter,1,True,"[_stat, ts, kalman-filter]"
341,_viz.dendrogram,1,True,"[_viz, dendrogram]"
342,_viz.waterfall-plot,1,True,"[_viz, waterfall-plot]"
1169,node.js,2,True,node.js
1270,pivottable.js,1,True,pivottable.js
1272,pixi.js,1,True,pixi.js
1298,povittable.js,1,True,povittable.js

In [137]:
tags_df

                      tag_in  count dot_check              tag_splits
0                 $chuckable     66     False            [$chuckable]
1           $chuckable(2016)      3     False      [$chuckable(2016)]
2                $read-often      4     False           [$read-often]
3                        $rr     50     False                   [$rr]
4                      &amp;      1     False                      []
5            &amp;amp;advice      2     False                [advice]
6           &amp;amp;article      5     False               [article]
7              &amp;amp;blog      2     False                  [blog]
8              &amp;amp;book      2     False                  [book]
9       &amp;amp;book-review      1     False           [book-review]
10     &amp;amp;cheat-sheets      2     False          [cheat-sheets]
11            &amp;amp;class      3     False                 [class]
12           &amp;amp;course      1     False                [course]
13    &amp;amp;documentation      2     False         [documentation]
14        &amp;amp;explainer      1     False             [explainer]
15            &amp;amp;guide      2     False                 [guide]
16           &amp;amp;how-to      3     False                [how-to]
17      &amp;amp;inspiration      1     False           [inspiration]
18             &amp;amp;list      1     False                  [list]
19     &amp;amp;long-article      2     False          [long-article]
20           &amp;amp;manual      3     False                [manual]
21         &amp;amp;merchant      1     False              [merchant]
22          &amp;amp;op_inst      1     False               [op_inst]
23            &amp;amp;paper      1     False                 [paper]
24              &amp;amp;pdf      1     False                   [pdf]
25            &amp;amp;prank      1     False                 [prank]
26          &amp;amp;present      1     False               [present]
27     &amp;amp;presentation      2     False          [presentation]
28           &amp;amp;primer      4     False                [primer]
29          &amp;amp;project      7     False               [project]
...                      ...    ...       ...                     ...
1712                    wiki      1     False                  [wiki]
1713               wikileaks      1     False             [wikileaks]
1714              win-vector      3     False            [win-vector]
1715                    wind      1     False                  [wind]
1716                 windows      8     False               [windows]
1717               winsorize      1     False             [winsorize]
1718                    wise     45     False                  [wise]
1719                 wolfram      3     False               [wolfram]
1720                    word      1     False                  [word]
1721                word2vec      3     False              [word2vec]
1722               wordcloud      7     False             [wordcloud]
1723                   words      1     False                 [words]
1724                    work      1     False                  [work]
1725                workflow      2     False              [workflow]
1726               workflows      1     False             [workflows]
1727            working-copy      1     False          [working-copy]
1728                 workout      1     False               [workout]
1729    worth-of-information      1     False  [worth-of-information]
1730                     wow      3     False                   [wow]
1731                 wrangle     11     False               [wrangle]
1732                 writing      5     False               [writing]
1733                   xcode      1     False                 [xcode]
1734                 xlwings      1     False               [xlwings]
1735                     xts      2     False                   [xts]
1736         y-aware_scaling      2     False       [y-aware_scaling]
1737                    yaml      3     False                  [yaml]
1738               yeah-boii      1     False             [yeah-boii]
1739                    yhat      8     False                  [yhat]
1740                     zen      1     False                   [zen]
1741                    zero      1     False                  [zero]

[1742 rows x 4 columns]

In [139]:
tags_df.to_csv("./data/tags_cleaned.csv")

## figure out POSTS data structue

In [7]:
posts_pb = pb.posts.all()
type(posts_pb)

list